services:
  configgymajiggy:
    build: .
    container_name: configgymajiggy-service
    ports:
      - "8080:8080"  # Expose on standard port, change left side for different external port
    environment:
      - RUST_LOG=info
    restart: unless-stopped  # Always restart unless manually stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      - /etc/localtime:/etc/localtime:ro  # Sync timezone with host
    networks:
      - configgymajiggy-network

networks:
  configgymajiggy-network:
    driver: bridge